title: Research Software Engineers International
#author: IntRSE
#email: info@nl-rse.org
description: > # this means to ignore newlines until "baseurl:"
  The website of the international RSE community
#twitter_username: nl_rse
github_username:  RSE-leaders

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - assoc.md
 - contact.md
# - communication.md

# Build settings
markdown: kramdown
theme: minima
